from schemas.AnimeSchema import AnimeCreateClass

A_L = [
    AnimeCreateClass(name="Атака титанов", create_data="2013", final_data="2023", count_of_series=111, genre="Экшен, Фэнтези, Драма"),
    AnimeCreateClass(name="Бездомный Бог", create_data="2014", final_data="2015", count_of_series=12, genre="Экшен, Сверхъестественное"),
    AnimeCreateClass(name="Битва через 5 секунд", create_data="2021", final_data="2021", count_of_series=12, genre="Экшен, Сверхъестественное"),
    AnimeCreateClass(name="Бродячие псы: Литературные гении", create_data="2016", final_data="2019", count_of_series=37, genre="Экшен, Детектив, Сверхъестественное"),
    AnimeCreateClass(name="Ванпанчмен", create_data="2015", final_data="2019", count_of_series=24, genre="Экшен, Комедия, Пародия"),
    AnimeCreateClass(name="Восхождение героя щита", create_data="2019", final_data="2022", count_of_series=38, genre="Экшен, Приключения, Драма"),
    AnimeCreateClass(name="Вторжение. ID", create_data="2023", final_data="2023", count_of_series=12, genre="Научная фантастика, Мистика"),
    AnimeCreateClass(name="Ди Грэй-мен", create_data="2006", final_data="2008", count_of_series=103, genre="Экшен, Ужасы, Сверхъестественное"),
    AnimeCreateClass(name="Доктор Стоун", create_data="2019", final_data="2022", count_of_series=69, genre="Научная фантастика, Приключения"),
    AnimeCreateClass(name="Досье лорда Эль-Меллоя II", create_data="2019", final_data="2019", count_of_series=13, genre="Детектив, Сверхъестественное"),
    AnimeCreateClass(name="Клинок, рассекающий демонов", create_data="2019", final_data="2023", count_of_series=55, genre="Экшен, Сверхъестественное, Историческое"),
    AnimeCreateClass(name="Лунное путешествие к новому миру", create_data="2023", final_data="2023", count_of_series=12, genre="Фэнтези, Приключения"),
    AnimeCreateClass(name="Лучший ассасин, переродившийся аристократом", create_data="2021", final_data="2021", count_of_series=12, genre="Экшен, Фэнтези, Реинкарнация"),
    AnimeCreateClass(name="Магическая битва", create_data="2020", final_data="2023", count_of_series=47, genre="Экшен, Сверхъестественное"),
    AnimeCreateClass(name="Мастера меча онлайн", create_data="2012", final_data="2020", count_of_series=96, genre="Экшен, Приключения, Романтика"),
    AnimeCreateClass(name="Моя геройская академия", create_data="2016", final_data="2023", count_of_series=138, genre="Экшен, Супергерои, Школа"),
    AnimeCreateClass(name="Необъятный океан", create_data="2023", final_data="2023", count_of_series=12, genre="Научная фантастика, Мистика"),
    AnimeCreateClass(name="О моём перерождении в слизь", create_data="2018", final_data="2021", count_of_series=48, genre="Фэнтези, Приключения"),
    AnimeCreateClass(name="Персиковый мальчик с другого берега", create_data="2023", final_data="2023", count_of_series=12, genre="Фэнтези, Приключения"),
    AnimeCreateClass(name="Плод эволюции", create_data="2022", final_data="2022", count_of_series=12, genre="Комедия, Фэнтези"),
    AnimeCreateClass(name="Полное погружение: RPG сложнее жизни", create_data="2021", final_data="2021", count_of_series=12, genre="Фэнтези, Приключения"),
    AnimeCreateClass(name="Последний Серафим", create_data="2015", final_data="2015", count_of_series=24, genre="Экшен, Сверхъестественное"),
    AnimeCreateClass(name="Реинкарнация безработного", create_data="2021", final_data="2021", count_of_series=23, genre="Фэнтези, Драма, Реинкарнация"),
    AnimeCreateClass(name="Розовая пора моей школьной жизни сплошной обман", create_data="2022", final_data="2022", count_of_series=13, genre="Драма, Романтика"),
    AnimeCreateClass(name="Синий Экзорцист", create_data="2011", final_data="2017", count_of_series=37, genre="Экшен, Сверхъестественное"),
    AnimeCreateClass(name="С нуля: Пособие по выживанию в альтернативном мире", create_data="2022", final_data="2022", count_of_series=20, genre="Фэнтези, Драма"),
    AnimeCreateClass(name="Стальной алхимик", create_data="2003", final_data="2004", count_of_series=51, genre="Экшен, Приключения, Драма"),
    AnimeCreateClass(name="Судьба: Девочка-волшебница Иллия", create_data="2013", final_data="2016", count_of_series=32, genre="Магия, Приключения"),
    AnimeCreateClass(name="Эта фарфоровая кукла влюбилась", create_data="2023", final_data="2023", count_of_series=12, genre="Романтика, Драма"),
    AnimeCreateClass(name="Этот глупый свин не понимает мечту девочки-зайки", create_data="2022", final_data="2022", count_of_series=12, genre="Комедия, Романтика"),
    AnimeCreateClass(name="Этот прекрасный мир", create_data="2016", final_data="2023", count_of_series=42, genre="Комедия, Фэнтези, Приключения"),
    AnimeCreateClass(name="Наруто", create_data="2002", final_data="2007", count_of_series=220, genre="Экшен, Приключения"),
    AnimeCreateClass(name="Убийца Акаме", create_data="2014", final_data="2014", count_of_series=24, genre="Экшен, Драма"),
    AnimeCreateClass(name="Акудама драйв", create_data="2020", final_data="2020", count_of_series=12, genre="Экшен, Научная фантастика"),
    AnimeCreateClass(name="Код Гиас", create_data="2006", final_data="2008", count_of_series=50, genre="Меха, Психологическое, Триллер"),
    AnimeCreateClass(name="Уж не зомби ли это", create_data="2011", final_data="2012", count_of_series=12, genre="Комедия, Сверхъестественное"),
    AnimeCreateClass(name="Вайолет Эвергарден", create_data="2018", final_data="2019", count_of_series=13, genre="Драма, Фэнтези"),
    AnimeCreateClass(name="Класс убийц", create_data="2023", final_data="2023", count_of_series=12, genre="Экшен, Школа"),
    AnimeCreateClass(name="Обещанный Неверленд", create_data="2019", final_data="2021", count_of_series=23, genre="Психологическое, Триллер, Драма"),
    AnimeCreateClass(name="Судьба: ночь схватки", create_data="2006", final_data="2006", count_of_series=24, genre="Экшен, Сверхъестественное"),
    AnimeCreateClass(name="Судьба: сад грешников", create_data="2013", final_data="2013", count_of_series=13, genre="Мистика, Драма"),
    AnimeCreateClass(name="Судьба: Повесть о лунной принцессе", create_data="2021", final_data="2021", count_of_series=1, genre="Фэнтези, Романтика"),
    AnimeCreateClass(name="Судьба: Начало", create_data="2011", final_data="2012", count_of_series=1, genre="Экшен, Фэнтези"),
    AnimeCreateClass(name="Судьба: Прототип", create_data="2011", final_data="2011", count_of_series=1, genre="Экшен, Фэнтези"),
    AnimeCreateClass(name="Судьба: Последний вызов на бис", create_data="2017", final_data="2017", count_of_series=1, genre="Экшен, Фэнтези"),
    AnimeCreateClass(name="Судьба: Апокриф", create_data="2017", final_data="2017", count_of_series=25, genre="Экшен, Фэнтези"),
    AnimeCreateClass(name="Судьба: Великий приказ", create_data="2019", final_data="2019", count_of_series=1, genre="Экшен, Фэнтези"),
    AnimeCreateClass(name="Аватар короля", create_data="2005", final_data="2008", count_of_series=61, genre="Приключения, Фэнтези"),
    AnimeCreateClass(name="Моб психо 100", create_data="2016", final_data="2022", count_of_series=37, genre="Комедия, Сверхъестественное"),
    AnimeCreateClass(name="Мешки и пушки", create_data="2018", final_data="2018", count_of_series=12, genre="Экшен, Научная фантастика"),
    AnimeCreateClass(name="Темный лорд альтернативная история", create_data="2022", final_data="2022", count_of_series=12, genre="Фэнтези, Исекай"),
    AnimeCreateClass(name="Джо Джо", create_data="2012", final_data="2022", count_of_series=190, genre="Экшен, Приключения"),
    AnimeCreateClass(name="Повелитель", create_data="2012", final_data="2015", count_of_series=13, genre="Комедия, Сверхъестественное"),
    AnimeCreateClass(name="Я стою на миллионе трупов", create_data="2020", final_data="2020", count_of_series=12, genre="Фэнтези, Приключения"),
    AnimeCreateClass(name="Токийский гуль", create_data="2014", final_data="2018", count_of_series=48, genre="Экшен, Ужасы, Драма"),
    AnimeCreateClass(name="Хантер Х Хантер", create_data="2011", final_data="2014", count_of_series=148, genre="Экшен, Приключения"),
    AnimeCreateClass(name="Нет игры - нет жизни", create_data="2014", final_data="2014", count_of_series=12, genre="Комедия, Фэнтези"),
    AnimeCreateClass(name="Дневник будущего", create_data="2011", final_data="2011", count_of_series=26, genre="Психологическое, Триллер"),
    AnimeCreateClass(name="Семь смертных грехов", create_data="2014", final_data="2021", count_of_series=100, genre="Экшен, Фэнтези"),
    AnimeCreateClass(name="Город в котором меня нет", create_data="2016", final_data="2016", count_of_series=12, genre="Психологическое, Триллер"),
    AnimeCreateClass(name="Паразит учение о жизни", create_data="2014", final_data="2015", count_of_series=24, genre="Ужасы, Психологическое"),
    AnimeCreateClass(name="Евангелион", create_data="1995", final_data="1996", count_of_series=26, genre="Меха, Психологическое"),
    AnimeCreateClass(name="Психопаспорт", create_data="2012", final_data="2019", count_of_series=41, genre="Научная фантастика, Психологическое"),
    AnimeCreateClass(name="Сатана на подработке", create_data="2022", final_data="2023", count_of_series=24, genre="Комедия, Фэнтези"),
    AnimeCreateClass(name="Может я встречу тебя в подземелье", create_data="2015", final_data="2023", count_of_series=61, genre="Фэнтези, Приключения"),
    AnimeCreateClass(name="Созданный в бездне", create_data="2017", final_data="2022", count_of_series=25, genre="Фэнтези, Приключения"),
    AnimeCreateClass(name="Кошечка из Сакурасо", create_data="2012", final_data="2013", count_of_series=24, genre="Драма, Романтика"),
    AnimeCreateClass(name="Этот герой неуязвим но очень осторожен", create_data="2019", final_data="2019", count_of_series=12, genre="Комедия, Фэнтези"),
    AnimeCreateClass(name="Гурен-Лаген", create_data="2007", final_data="2007", count_of_series=27, genre="Меха, Научная фантастика"),
    AnimeCreateClass(name="Судьба: Клинков бесконечный край", create_data="2010", final_data="2010", count_of_series=1, genre="Экшен, Фэнтези"),
    AnimeCreateClass(name="Убийца гоблинов", create_data="2018", final_data="2018", count_of_series=13, genre="Экшен, Фэнтези"),
    AnimeCreateClass(name="Чёрная пуля", create_data="2014", final_data="2014", count_of_series=13, genre="Экшен, Научная фантастика"),
    AnimeCreateClass(name="Стражи барьера", create_data="2020", final_data="2020", count_of_series=12, genre="Фэнтези, Приключения"),
    AnimeCreateClass(name="91 день", create_data="2016", final_data="2016", count_of_series=12, genre="Драма, Историческое"),
    AnimeCreateClass(name="Марш смерти под рапсодию параллельного мира", create_data="2023", final_data="2023", count_of_series=12, genre="Фэнтези, Приключения"),
    AnimeCreateClass(name="Убивала слизней 300 лет", create_data="2021", final_data="2021", count_of_series=12, genre="Комедия, Фэнтези"),
    AnimeCreateClass(name="Корона грешника", create_data="2022", final_data="2022", count_of_series=12, genre="Фэнтези, Драма"),
    AnimeCreateClass(name="Твоя апрельская ложь", create_data="2014", final_data="2015", count_of_series=22, genre="Драма, Романтика"),
    AnimeCreateClass(name="Меня выгнали из гильдии потому что я был плохим компаньоном поэтому я решил неспешно жить в глуши", create_data="2023", final_data="2023", count_of_series=12, genre="Фэнтези, Приключения"),
    AnimeCreateClass(name="Твоё имя", create_data="2016", final_data="2016", count_of_series=1, genre="Романтика, Драма"),
    AnimeCreateClass(name="Дитя погоды", create_data="2019", final_data="2019", count_of_series=1, genre="Фэнтези, Драма"),
    AnimeCreateClass(name="Эхо террора", create_data="2023", final_data="2023", count_of_series=12, genre="Триллер, Психологическое"),
    AnimeCreateClass(name="Школа мертвецов", create_data="2013", final_data="2013", count_of_series=12, genre="Ужасы, Экшен"),
    AnimeCreateClass(name="Мастерство копа", create_data="2022", final_data="2022", count_of_series=12, genre="Комедия, Фэнтези"),
    AnimeCreateClass(name="Шаман кинг", create_data="2001", final_data="2002", count_of_series=64, genre="Экшен, Приключения"),
    AnimeCreateClass(name="Ремейк нашей жизни", create_data="2021", final_data="2021", count_of_series=12, genre="Драма, Романтика"),
    AnimeCreateClass(name="Любимый во франксе", create_data="2018", final_data="2018", count_of_series=24, genre="Меха, Драма"),
    AnimeCreateClass(name="Чёрный клевер", create_data="2017", final_data="2021", count_of_series=170, genre="Экшен, Фэнтези"),
    AnimeCreateClass(name="Ходячий замок", create_data="2004", final_data="2004", count_of_series=1, genre="Фэнтези, Романтика"),
    AnimeCreateClass(name="Клан девяти", create_data="2023", final_data="2023", count_of_series=12, genre="Экшен, Фэнтези"),
    AnimeCreateClass(name="Внук мудреца", create_data="2022", final_data="2022", count_of_series=12, genre="Фэнтези, Приключения"),
    AnimeCreateClass(name="Книга магии для начинающих с нуля", create_data="2021", final_data="2021", count_of_series=12, genre="Фэнтези, Приключения"),
    AnimeCreateClass(name="Маги: Магический лабиринт", create_data="2012", final_data="2012", count_of_series=25, genre="Фэнтези, Приключения"),
    AnimeCreateClass(name="Маги: Королевство магии", create_data="2013", final_data="2013", count_of_series=25, genre="Фэнтези, Приключения"),
    AnimeCreateClass(name="Маги: Приключения Синбада", create_data="2016", final_data="2016", count_of_series=13, genre="Фэнтези, Приключения"),
    AnimeCreateClass(name="Шаман кинг (2021)", create_data="2021", final_data="2022", count_of_series=52, genre="Экшен, Приключения"),
    AnimeCreateClass(name="Крутой учитель Онидзука", create_data="1999", final_data="2000", count_of_series=43, genre="Комедия, Драма"),
    AnimeCreateClass(name="Маг на полную ставку", create_data="2020", final_data="2020", count_of_series=12, genre="Фэнтези, Комедия"),
    AnimeCreateClass(name="Хвост феи", create_data="2009", final_data="2019", count_of_series=328, genre="Экшен, Фэнтези"),
    AnimeCreateClass(name="Парад смерти", create_data="2015", final_data="2015", count_of_series=12, genre="Психологическое, Триллер"),
    AnimeCreateClass(name="Патриотизм Мариарти", create_data="2020", final_data="2021", count_of_series=24, genre="Детектив, Историческое"),
    AnimeCreateClass(name="Билд Дивайд", create_data="2022", final_data="2022", count_of_series=12, genre="Экшен, Научная фантастика"),
    AnimeCreateClass(name="Непутёвый ученик в школе магии", create_data="2021", final_data="2021", count_of_series=13, genre="Фэнтези, Школа"),
    AnimeCreateClass(name="Из завтрашнего дня разноцветного мира", create_data="2019", final_data="2019", count_of_series=1, genre="Драма, Фэнтези"),
    AnimeCreateClass(name="Плеяда 7 звёзд", create_data="2021", final_data="2021", count_of_series=12, genre="Фэнтези, Приключения"),
    AnimeCreateClass(name="Буря потерь", create_data="2022", final_data="2022", count_of_series=13, genre="Драма, Психологическое"),
    AnimeCreateClass(name="Удар крови", create_data="2014", final_data="2014", count_of_series=12, genre="Экшен, Сверхъестественное"),
    AnimeCreateClass(name="Корзинка фруктов", create_data="2001", final_data="2001", count_of_series=26, genre="Романтика, Драма"),
    AnimeCreateClass(name="Восхождение чародея", create_data="2023", final_data="2023", count_of_series=13, genre="Фэнтези, Приключения"),
    AnimeCreateClass(name="Log horizon", create_data="2013", final_data="2021", count_of_series=43, genre="Фэнтези, Приключения"),
    AnimeCreateClass(name="Привлекая поцелуй", create_data="2022", final_data="2022", count_of_series=12, genre="Романтика, Комедия"),
    AnimeCreateClass(name="Киберпанк: Бегущие по краю", create_data="2022", final_data="2022", count_of_series=10, genre="Научная фантастика, Экшен"),
    AnimeCreateClass(name="Пираты Черной лагуны", create_data="2006", final_data="2006", count_of_series=24, genre="Экшен, Приключения"),
    AnimeCreateClass(name="Дочь моей мачехи - моя бывшая девушка", create_data="2022", final_data="2022", count_of_series=12, genre="Романтика, Драма"),
    AnimeCreateClass(name="Заметки робототехника", create_data="2023", final_data="2023", count_of_series=12, genre="Научная фантастика, Комедия"),
    AnimeCreateClass(name="Врата штейна", create_data="2011", final_data="2011", count_of_series=24, genre="Научная фантастика, Триллер"),
    AnimeCreateClass(name="Черный призыватель", create_data="2017", final_data="2017", count_of_series=12, genre="Фэнтези, Приключения"),
    AnimeCreateClass(name="Арифурэта: Сильнейший в мире ремесленник", create_data="2019", final_data="2022", count_of_series=25, genre="Фэнтези, Экшен"),
    AnimeCreateClass(name="5 см в секунду", create_data="2007", final_data="2007", count_of_series=1, genre="Романтика, Драма"),
    AnimeCreateClass(name="Форма голоса", create_data="2016", final_data="2016", count_of_series=1, genre="Драма, Романтика"),
    AnimeCreateClass(name="Пламенная бригада пожарных", create_data="2019", final_data="2020", count_of_series=48, genre="Экшен, Научная фантастика"),
    AnimeCreateClass(name="Не люблю боль, поэтому вкачаю все в защиту", create_data="2020", final_data="2020", count_of_series=12, genre="Фэнтези, Комедия"),
    AnimeCreateClass(name="Башня бога", create_data="2020", final_data="2020", count_of_series=13, genre="Фэнтези, Приключения"),
    AnimeCreateClass(name="Токийские мстители", create_data="2021", final_data="2023", count_of_series=37, genre="Экшен, Драма"),
    AnimeCreateClass(name="Никчемный учитель магии: Хроники Акаши", create_data="2023", final_data="2023", count_of_series=12, genre="Фэнтези, Школа"),
    AnimeCreateClass(name="Класс превосходства", create_data="2023", final_data="2023", count_of_series=12, genre="Экшен, Фэнтези"),
    AnimeCreateClass(name="Повседневная жизнь бессмертного короля", create_data="2020", final_data="2021", count_of_series=30, genre="Комедия, Фэнтези"),
    AnimeCreateClass(name="Непризнанный школой владыка демонов", create_data="2023", final_data="2023", count_of_series=12, genre="Комедия, Фэнтези"),
    AnimeCreateClass(name="Маг-целитель: новый старт", create_data="2023", final_data="2023", count_of_series=12, genre="Фэнтези, Драма"),
    AnimeCreateClass(name="Агент времени", create_data="2023", final_data="2023", count_of_series=12, genre="Научная фантастика, Экшен"),
    AnimeCreateClass(name="Братство черной крови", create_data="2020", final_data="2020", count_of_series=12, genre="Экшен, Фэнтези"),
    AnimeCreateClass(name="Платиновый предел", create_data="2023", final_data="2023", count_of_series=12, genre="Научная фантастика, Экшен"),
    AnimeCreateClass(name="О моем перерождении в меч", create_data="2022", final_data="2022", count_of_series=12, genre="Фэнтези, Комедия"),
    AnimeCreateClass(name="Семья шпиона", create_data="2022", final_data="2023", count_of_series=37, genre="Комедия, Экшен"),
    AnimeCreateClass(name="Детектив уже мертв", create_data="2021", final_data="2021", count_of_series=12, genre="Детектив, Приключения"),
    AnimeCreateClass(name="Почетная ученица в школе магии", create_data="2021", final_data="2021", count_of_series=12, genre="Фэнтези, Школа"),
    AnimeCreateClass(name="Алый нексус", create_data="2022", final_data="2022", count_of_series=12, genre="Экшен, Фэнтези"),
    AnimeCreateClass(name="Виви: Песнь флюоритового глаза", create_data="2023", final_data="2023", count_of_series=13, genre="Фэнтези, Драма"),
    AnimeCreateClass(name="Вампир в саду", create_data="2022", final_data="2022", count_of_series=5, genre="Фэнтези, Драма"),
    AnimeCreateClass(name="Жизнь перерожденного мудреца в другом мире", create_data="2021", final_data="2021", count_of_series=12, genre="Фэнтези, Исекай"),
    AnimeCreateClass(name="Величайший повелитель демонов перерождается как типичное ничтожество", create_data="2022", final_data="2022", count_of_series=12, genre="Фэнтези, Комедия"),
    AnimeCreateClass(name="Ориент", create_data="2022", final_data="2022", count_of_series=24, genre="Экшен, Фэнтези"),
    AnimeCreateClass(name="Человек-бензопила", create_data="2022", final_data="2022", count_of_series=12, genre="Экшен, Драма"),
    AnimeCreateClass(name="В симуляторе свиданий: Нелегкая жизнь мобов в мире отомэ-игр", create_data="2023", final_data="2023", count_of_series=12, genre="Комедия, Романтика"),
    AnimeCreateClass(name="Восемьдесят шесть", create_data="2021", final_data="2021", count_of_series=23, genre="Научная фантастика, Драма"),
    AnimeCreateClass(name="Повторная жизнь", create_data="2021", final_data="2021", count_of_series=12, genre="Драма, Фэнтези"),
    AnimeCreateClass(name="Мемуары Ванитаса", create_data="2021", final_data="2022", count_of_series=24, genre="Фэнтези, Драма"),
    AnimeCreateClass(name="Больше, чем пара, меньше, чем любовники", create_data="2022", final_data="2022", count_of_series=12, genre="Романтика, Драма"),
    AnimeCreateClass(name="Госпожа Кагуя: В любви как на войне", create_data="2019", final_data="2022", count_of_series=37, genre="Комедия, Романтика"),
    AnimeCreateClass(name="Девочка-волшебница Мадока", create_data="2011", final_data="2011", count_of_series=12, genre="Магия, Психологическое"),
    AnimeCreateClass(name="Мастера Меча Онлайн: Альтернативная «Призрачная пуля»", create_data="2014", final_data="2014", count_of_series=14, genre="Экшен, Приключения"),
    AnimeCreateClass(name="Межвидовые Рецензенты", create_data="2020", final_data="2020", count_of_series=12, genre="Комедия, Фэнтези"),
    AnimeCreateClass(name="Врата: Там бьются наши войны", create_data="2015", final_data="2016", count_of_series=24, genre="Фэнтези, Экшен"),
    AnimeCreateClass(name="Незнакомец на берегу моря", create_data="2023", final_data="2023", count_of_series=12, genre="Драма, Романтика"),
    AnimeCreateClass(name="Бесконечный Дендрограм", create_data="2020", final_data="2020", count_of_series=13, genre="Фэнтези, Приключения"),
    AnimeCreateClass(name="Полноценная жизнь онлайн", create_data="2021", final_data="2021", count_of_series=12, genre="Фэнтези, Комедия"),
    AnimeCreateClass(name="Убийственная любовь", create_data="2022", final_data="2022", count_of_series=12, genre="Комедия, Романтика"),
    AnimeCreateClass(name="У Коми проблемы с общением", create_data="2022", final_data="2022", count_of_series=24, genre="Комедия, Романтика"),
    AnimeCreateClass(name="Фармацевт из параллельного мира", create_data="2023", final_data="2023", count_of_series=12, genre="Фэнтези, Приключения"),
    AnimeCreateClass(name="Добро пожаловать на паркет", create_data="2020", final_data="2020", count_of_series=11, genre="Танцы, Драма"),
    AnimeCreateClass(name="Призрак лета", create_data="2020", final_data="2020", count_of_series=1, genre="Драма, Сверхъестественное"),
    AnimeCreateClass(name="Баскетбол Куроко", create_data="2012", final_data="2015", count_of_series=75, genre="Спорт, Комедия"),
    AnimeCreateClass(name="Хоримия", create_data="2021", final_data="2021", count_of_series=13, genre="Романтика, Комедия"),
    AnimeCreateClass(name="Ложные выводы", create_data="2023", final_data="2023", count_of_series=12, genre="Драма, Психологическое"),
    AnimeCreateClass(name="Чудачества любви не помеха", create_data="2022", final_data="2022", count_of_series=12, genre="Романтика, Комедия"),
    AnimeCreateClass(name="Восхождение в тени", create_data="2022", final_data="2023", count_of_series=32, genre="Фэнтези, Комедия"),
    AnimeCreateClass(name="ТораДора", create_data="2008", final_data="2009", count_of_series=25, genre="Романтика, Комедия"),
    AnimeCreateClass(name="Рыбка бананка", create_data="2022", final_data="2022", count_of_series=11, genre="Драма, Сверхъестественное"),
    AnimeCreateClass(name="Повар боец Сома", create_data="2015", final_data="2020", count_of_series=86, genre="Кулинария, Комедия"),
    AnimeCreateClass(name="Ангел по соседству", create_data="2023", final_data="2023", count_of_series=12, genre="Романтика, Комедия"),
    AnimeCreateClass(name="Песнь ночных сов", create_data="2022", final_data="2022", count_of_series=13, genre="Фэнтези, Приключения"),
    AnimeCreateClass(name="Внук Нурарихена", create_data="2010", final_data="2011", count_of_series=26, genre="Комедия, Сверхъестественное"),
    AnimeCreateClass(name="Ускоренный мир", create_data="2012", final_data="2012", count_of_series=24, genre="Научная фантастика, Экшен"),
    AnimeCreateClass(name="Старшая карта", create_data="2021", final_data="2021", count_of_series=12, genre="Драма, Школа"),
    AnimeCreateClass(name="Реинкарнация сильнейшего оммёдзи", create_data="2023", final_data="2023", count_of_series=13, genre="Фэнтези, Комедия"),
    AnimeCreateClass(name="Авантюристы, которые не верят в человечество, спасут мир", create_data="2023", final_data="2023", count_of_series=12, genre="Фэнтези, Приключения"),
    AnimeCreateClass(name="Томо - Девушка", create_data="2022", final_data="2022", count_of_series=1, genre="Комедия, Романтика"),
    AnimeCreateClass(name="Детективы Футо", create_data="2023", final_data="2023", count_of_series=12, genre="Детектив, Комедия"),
    AnimeCreateClass(name="Перевоплотившийся король-герой, ставший самой сильной ученицей рыцаря", create_data="2023", final_data="2023", count_of_series=12, genre="Фэнтези, Экшен"),
    AnimeCreateClass(name="Запретная татуировка", create_data="2023", final_data="2023", count_of_series=12, genre="Экшен, Фэнтези"),
    AnimeCreateClass(name="Великий притворщик", create_data="2023", final_data="2023", count_of_series=23, genre="Детектив, Драма"),
    AnimeCreateClass(name="Повесть о конце света", create_data="2023", final_data="2023", count_of_series=12, genre="Фэнтези, Драма"),
    AnimeCreateClass(name="Игра друзей", create_data="2022", final_data="2022", count_of_series=12, genre="Психологическое, Триллер"),
    AnimeCreateClass(name="Единственному мне, кто тебя любил", create_data="2022", final_data="2022", count_of_series=1, genre="Драма, Романтика"),
    AnimeCreateClass(name="Для каждой тебя, что я раньше любил", create_data="2022", final_data="2022", count_of_series=1, genre="Драма, Романтика"),
    AnimeCreateClass(name="Пингвиний барабан", create_data="2011", final_data="2011", count_of_series=24, genre="Драма, Психологическое"),
    AnimeCreateClass(name="Великолепный парк Амаги", create_data="2012", final_data="2012", count_of_series=13, genre="Комедия, Школа"),
    AnimeCreateClass(name="Папаши-напарники", create_data="2023", final_data="2023", count_of_series=12, genre="Комедия, Повседневность"),
    AnimeCreateClass(name="Герой мертв!", create_data="2023", final_data="2023", count_of_series=12, genre="Фэнтези, Комедия"),
    AnimeCreateClass(name="Одаривая этот замечательный мир взрывами", create_data="2023", final_data="2023", count_of_series=12, genre="Фэнтези, Комедия"),
    AnimeCreateClass(name="Звездное дитя", create_data="2022", final_data="2022", count_of_series=1, genre="Драма, Музыка"),
    AnimeCreateClass(name="Магия и мускулы", create_data="2023", final_data="2023", count_of_series=12, genre="Комедия, Фэнтези"),
    AnimeCreateClass(name="Адский рай", create_data="2023", final_data="2023", count_of_series=13, genre="Фэнтези, Драма"),
    AnimeCreateClass(name="Моя любовь к Ямаде 999 уровня", create_data="2023", final_data="2023", count_of_series=24, genre="Романтика, Комедия"),
    AnimeCreateClass(name="Читерский навык из другого мира сделал меня непобедимым в моём", create_data="2023", final_data="2023", count_of_series=12, genre="Фэнтези, Исекай"),
    AnimeCreateClass(name="Смертельная игра Мёртвой горы", create_data="2023", final_data="2023", count_of_series=13, genre="Экшен, Триллер"),
    AnimeCreateClass(name="Повелитель тьмы с последней парты", create_data="2023", final_data="2023", count_of_series=12, genre="Комедия, Фэнтези"),
    AnimeCreateClass(name="Призванный в другой мир во второй раз", create_data="2023", final_data="2023", count_of_series=12, genre="Фэнтези, Исекай"),
    AnimeCreateClass(name="Невеста чародея", create_data="2023", final_data="2023", count_of_series=12, genre="Фэнтези, Романтика"),
    AnimeCreateClass(name="Великая небесная стена", create_data="2023", final_data="2023", count_of_series=12, genre="Фэнтези, Приключения"),
    AnimeCreateClass(name="Волшебник-воин Орфен", create_data="2020", final_data="2021", count_of_series=24, genre="Фэнтези, Приключения"),
    AnimeCreateClass(name="Одинокий рокер", create_data="2022", final_data="2022", count_of_series=12, genre="Музыка, Драма"),
    AnimeCreateClass(name="Синтетические воспоминания", create_data="2023", final_data="2023", count_of_series=12, genre="Научная фантастика, Драма"),
    AnimeCreateClass(name="Из мечтателя в реалиста", create_data="2023", final_data="2023", count_of_series=12, genre="Драма, Романтика"),
    AnimeCreateClass(name="Месть Масамунэ", create_data="2017", final_data="2017", count_of_series=12, genre="Романтика, Комедия"),
    AnimeCreateClass(name="Лжец, Лжец", create_data="2023", final_data="2023", count_of_series=12, genre="Комедия, Школа"),
    AnimeCreateClass(name="Спокойной ночи мир", create_data="2023", final_data="2023", count_of_series=9, genre="Драма, Психологическое"),
    AnimeCreateClass(name="Притворная любовь", create_data="2023", final_data="2023", count_of_series=12, genre="Романтика, Драма"),
    AnimeCreateClass(name="Магия вернувшегося должна быть особенной", create_data="2023", final_data="2023", count_of_series=12, genre="Фэнтези, Драма"),
    AnimeCreateClass(name="Парадокс в прямом эфире", create_data="2023", final_data="2023", count_of_series=12, genre="Триллер, Психологическое"),
    AnimeCreateClass(name="Паладин издалека", create_data="2021", final_data="2021", count_of_series=12, genre="Фэнтези, Драма"),
    AnimeCreateClass(name="Рон Камонохаси: Невменяемый детектив", create_data="2023", final_data="2023", count_of_series=13, genre="Детектив, Комедия"),
    AnimeCreateClass(name="Этот глупый свин не понимает чувства сестры на прогулке", create_data="2023", final_data="2023", count_of_series=12, genre="Комедия, Романтика"),
    AnimeCreateClass(name="Искушенная ты и неопытный я", create_data="2023", final_data="2023", count_of_series=12, genre="Романтика, Драма"),
    AnimeCreateClass(name="Предсмертный список зомби", create_data="2023", final_data="2023", count_of_series=12, genre="Комедия, Сверхъестественное"),
    AnimeCreateClass(name="Сто девушек, которые очень-очень-очень-очень-очень меня любят", create_data="2023", final_data="2023", count_of_series=12, genre="Комедия, Романтика"),
    AnimeCreateClass(name="Низко квалифицированный ниндзя", create_data="2023", final_data="2023", count_of_series=12, genre="Комедия, Фэнтези"),
    AnimeCreateClass(name="Монолог Фармацевта", create_data="2023", final_data="2023", count_of_series=48, genre="Фэнтези, Драма"),
    AnimeCreateClass(name="Неправильный способ использования исцеляющей магии", create_data="2024", final_data="2024", count_of_series=12, genre="Фэнтези, Комедия"),
    AnimeCreateClass(name="Синдуальность: Нуар", create_data="2023", final_data="2023", count_of_series=12, genre="Научная фантастика, Экшен"),
    AnimeCreateClass(name="Королева, ставшая причиной трагедии, сделает для народа всё, что в её силах", create_data="2023", final_data="2023", count_of_series=12, genre="Фэнтези, Драма"),
    AnimeCreateClass(name="Поднятие уровня в одиночку", create_data="2023", final_data="2023", count_of_series=12, genre="Фэнтези, Экшен"),
    AnimeCreateClass(name="Опасность в моем сердце", create_data="2023", final_data="2023", count_of_series=12, genre="Романтика, Комедия"),
    AnimeCreateClass(name="Ликорис Рикоил", create_data="2022", final_data="2022", count_of_series=13, genre="Экшен, Научная фантастика"),
    AnimeCreateClass(name="Путь домохозяна", create_data="2021", final_data="2021", count_of_series=12, genre="Комедия, Повседневность"),
    AnimeCreateClass(name="Нежеланно бессмертный авантюрист", create_data="2023", final_data="2023", count_of_series=12, genre="Фэнтези, Приключения"),
    AnimeCreateClass(name="Ковбой Бибоп", create_data="1998", final_data="1999", count_of_series=26, genre="Научная фантастика, Экшен"),
    AnimeCreateClass(name="Рагна Багровый", create_data="2023", final_data="2023", count_of_series=24, genre="Фэнтези, Экшен"),
    AnimeCreateClass(name="Кайдзю номер 8", create_data="2024", final_data="2024", count_of_series=12, genre="Экшен, Научная фантастика"),
    AnimeCreateClass(name="Бармен бакал бога", create_data="2022", final_data="2022", count_of_series=12, genre="Фэнтези, Драма"),
    AnimeCreateClass(name="Меч и жезл вистории", create_data="2023", final_data="2023", count_of_series=12, genre="Фэнтези, Приключения"),
    AnimeCreateClass(name="Отряд самоубийц из другого мира", create_data="2023", final_data="2023", count_of_series=12, genre="Фэнтези, Экшен"),
    AnimeCreateClass(name="Я получил читерские способности в другом мире", create_data="2023", final_data="2023", count_of_series=12, genre="Фэнтези, Исекай"),
    AnimeCreateClass(name="Летнее время", create_data="2023", final_data="2023", count_of_series=13, genre="Драма, Романтика"),
    AnimeCreateClass(name="Рубеж Шангри Ла", create_data="2023", final_data="2023", count_of_series=12, genre="Научная фантастика, Приключения"),
    AnimeCreateClass(name="Повелитель демонов 2099", create_data="2023", final_data="2023", count_of_series=12, genre="Научная фантастика, Экшен"),
    AnimeCreateClass(name="Полное исследование", create_data="2023", final_data="2023", count_of_series=12, genre="Научная фантастика, Драма"),
    AnimeCreateClass(name="Лазарь", create_data="2023", final_data="2023", count_of_series=13, genre="Научная фантастика, Триллер"),
    AnimeCreateClass(name="Гуррен-Лаганн", create_data="2007", final_data="2007", count_of_series=27, genre="Меха, Научная фантастика"),
    AnimeCreateClass(name="Моя геройская академия: Вне закона", create_data="2022", final_data="2022", count_of_series=13, genre="Экшен, Супергерои"),
    AnimeCreateClass(name="Магистр дьявольского культа", create_data="2018", final_data="2019", count_of_series=35, genre="Фэнтези, Драма"),
    AnimeCreateClass(name="Перерождение Дяди", create_data="2021", final_data="2021", count_of_series=13, genre="Комедия, Фэнтези"),
    AnimeCreateClass(name="Супер куб", create_data="2021", final_data="2021", count_of_series=12, genre="Научная фантастика, Триллер"),
]

